### PR TITLE
Added missing parameters to Group, Event, and Location classes

### PR DESCRIPTION
**Pull request by bradbamford**
Added missing properties, fixes Issues #7, #8, and #9

### CODE REVIEW

**Comment by bradbamford** [comment]
@chadman Hey Chad, any chance you can merge these missing properties into the project sometime soon?

**Comment by davidshq** [comment]
@chadman @bradbamford what happened to this project?

**Comment by bradbamford** [comment]
I don't know @davidshq because this isn't my project and I have no access to it. I did fix several items and submitted pull requests but they never were added in. I think @chadman has moved on so I've just started using my own fork of the project that contains bug fixes and newer features of the CCB API. I've kept my fixes separated into feature branches hoping to get them merged back into this project so there can be real collaboration which would be nice. I'm currently using a 'Full-Featured' branch in production that contains all my feature pull-request branches. Hopefully, @chadman will chime in on how we can somehow work together on this project or put it to bed at least.

**Comment by davidshq** [comment]
@bradbamford - appears our wish has been granted! Thanks @chadman!

**Pull request merged**
